[WIP] Add onboarding and offboarding procedures for cocc members
kubernetes/community pull request #5126
Opened 2020-09-10 22:20 UTC by celestehorgan

Signed-off-by: Celeste Horgan <celeste@cncf.io>

Document the (known) onboarding and offboarding procedures for Code of Conduct Committee members

**Which issue(s) this PR fixes**:

Fixes https://github.com/kubernetes/community/issues/3954

cc: @tpepper @karenhchu @AevaOnline @tashimi – please check this for completion!

2020-09-14 18:55 UTC, AevaOnline commented on committee-code-of-conduct/governance/onboarding-offboarding.md
> +- [ ] Update `kubernetes/k8s.io` [`groups.yaml`](https://github.com/kubernetes/k8s.io/blob/ca864e62da1d38832d3026da3021f0cbf156dd1d/groups/groups.yaml)
link points to a specific SHA rather than current branch.

2020-09-14 18:56 UTC, AevaOnline commented on committee-code-of-conduct/governance/onboarding-offboarding.md
> +    > **Note:** This permission controls access to the mailing list and Google Drive!
hah! yea, we learned the hard way this time.

Could we add a note explicitly saying that direct changes to mailing list and drive will be reverted by the automation?

2020-09-14 19:04 UTC, AevaOnline commented on committee-code-of-conduct/governance/onboarding-offboarding.md
> +Permissions in this
I'm unsure what this line is about, and it looks incomplete?

2020-09-14 19:04 UTC, AevaOnline commented
Thanks, Celeste! I really appreciate that this process is getting written down. A couple minor things come to mind that could be added, in addition to my inline comments.

- schedule knowledge transfer and training sessions for new committee members
- re-evaluate regular meeting time to see if it works for the new group

2020-09-24 00:58 UTC, celestehorgan commented
@AevaOnline updated! Take a look when you have a moment :)

2020-09-24 00:58 UTC, celestehorgan commented
/remove work-in-progress

2020-09-29 21:34 UTC, celestehorgan commented
/lgtm

2020-09-29 21:38 UTC, karenhchu commented
/lgtm

2020-09-29 21:43 UTC, merged

2020-09-29 21:54 UTC, tpepper requested changes
Doh.  I'm slow on commenting versus the lgtm that merged this.  Can we iterate?

2020-09-29 21:54 UTC, tpepper commented on committee-code-of-conduct/governance/onboarding-offboarding.md
> +**Who executes:** When offboarding, outgoing members must remove themselves from Slack channels. When onboarding, carryover members must add incoming members.
Also note incoming members toggle on notifications for the channels?

2020-09-29 21:54 UTC, tpepper commented on committee-code-of-conduct/governance/onboarding-offboarding.md
> +    > **Note:** This file controls access to the mailing list and Google Drive! If you do not update this file, adding people manually (via the UIs) continually revert until this file is updated.
Should note using https://cs.k8s.io/ to search out additional places.  I updated OWNERS_ALIASES in k/k8s.io, k/org, and k/test-infra.

2020-09-29 21:54 UTC, tpepper commented on committee-code-of-conduct/governance/onboarding-offboarding.md
> +
Suggest adding something like:

```
### Zoom

**Who ...**
- [ ] Rotate meeting passcode and hostid
- [ ] Share new hostid with new members
```

2020-09-29 21:54 UTC, tpepper commented on committee-code-of-conduct/governance/onboarding-offboarding.md
> +- [ ] Code of conduct committee Slack channel on `kubernetes.slack.com`
Should this list specific #channel names for clarity?  We were added to two in the k8s slack.

2020-09-29 21:54 UTC, tpepper commented on committee-code-of-conduct/governance/onboarding-offboarding.md
> +    > **Note:** This file controls access to the mailing list and Google Drive! If you do not update this file, adding people manually (via the UIs) continually revert until this file is updated.
Suggest changing "Google Drive" to "Google folder share" or whatever is the right Google Noun for that.  We don't have a Google Drive.