[WIP] updating contributing.md
kubernetes/community pull request #5224
Opened 2020-10-15 20:53 UTC by celanthe

Updating contributing.md to adhere to K8s Developer Style Guide

2020-10-15 20:54 UTC, celanthe commented
/assign @celanthe

2020-10-15 20:59 UTC, celanthe commented
/uncc @tpepper @guineveresaenger

2020-10-15 21:07 UTC, celanthe commented
/assign @mrbobbytables @castrojo

2020-10-19 13:30 UTC, mrbobbytables requested changes
Thanks @celanthe :)
I've made some suggestions, mostly link fixes.

2020-10-19 13:30 UTC, mrbobbytables commented on contributors/guide/contributing.md
> +[test flakes]: http://velodrome.k8s.io/dashboard/db/bigquery-metrics?orgId=1
```suggestion
[test flakes]: /contributors/devel/sig-testing/flaky-tests.md#flaky-tests
```
References to velodrome were removed in https://github.com/kubernetes/community/pull/5193 It'd probably be better to link directly to the flakey test docs.

2020-10-19 13:30 UTC, mrbobbytables commented on contributors/guide/contributing.md
> +[good commit messages]: https://chris.beams.io/posts/git-commit/
```suggestion
[good commit messages]: ./pull-requests.md#commit-message-guidelines
```
We have our own updated section on commit message best practices now \o/

2020-10-19 13:30 UTC, mrbobbytables commented on contributors/guide/contributing.md
> +[coding conventions]: coding-conventions.md
```suggestion
[coding conventions]: ./coding-conventions.md
```

2020-10-19 13:30 UTC, mrbobbytables commented on contributors/guide/contributing.md
> +[scalability best practices]: scalability-good-practices.md
```suggestion
[scalability best practices]: ./scalability-good-practices.md
```

2020-10-19 13:30 UTC, mrbobbytables commented on contributors/guide/contributing.md
> +[keywords]: https://help.github.com/en/articles/closing-issues-using-keywords
```suggestion
[keywords]: ./pull-requests.md#do-not-use-github-keywords-or-mentions-within-your-commit-message
```
We've now integrated the docs and tailored them to the project 👍

2020-10-19 13:30 UTC, mrbobbytables commented on contributors/guide/contributing.md
> +[Squashing Git Commits]: https://davidwalsh.name/squash-commits-git
```suggestion
[Squashing Git Commits]: ./pull-requests.md#squashing
```

2020-10-19 13:30 UTC, mrbobbytables commented on contributors/guide/contributing.md
> +grammar fix), please squash your commits so that we can maintain a cleaner gGit
```suggestion
grammar fix), please squash your commits so that we can maintain a cleaner Git 
```

2020-10-19 13:30 UTC, mrbobbytables commented on contributors/guide/contributing.md
> +more information.
```suggestion
Refer to the [Issue Triage Guidelines] for  more information.
```

2020-10-19 13:30 UTC, mrbobbytables commented on contributors/guide/contributing.md
> +- [Open a Pull Request](#open-a-pull-request)
```suggestion
- [Opening a Pull Request](#opening-a-pull-request)
```
Fixes link

2020-10-23 18:40 UTC, celanthe commented on contributors/guide/contributing.md
> +It is best to contact a [SIG] for issues related to that SIG's topic. A SIG
Hi @mrbobbytables  -- I've accepted all your commit suggestions, please take a look! TYSM! :)

2020-11-03 19:42 UTC, celanthe commented
/close

2020-11-03 19:42 UTC, closed without merging