Add jeremyrickard to sig-release slack groups
kubernetes/community pull request #5407
Opened 2021-01-14 01:29 UTC by hasheddan

Adds @jeremyrickard to sig-release slack groups as part of technical lead
onboarding.

Signed-off-by: hasheddan <georgedanielmangum@gmail.com>

**Which issue(s) this PR fixes**:

xref https://github.com/kubernetes/sig-release/issues/1421

/hold
/assign @justaugustus @saschagrunert

2021-01-14 02:13 UTC, justaugustus requested changes
@hasheddan -- Roughly the same review ashttps://github.com/kubernetes/k8s.io/pull/1529#pullrequestreview-567793308.

There are a few of us in @kubernetes/sig-release-leads that hold multiple roles...
Yourself, @saschagrunert, and I are:

- SIG leadership
- Release Managers
- RelEng subproject owners

We need to codify this somewhere, but I've been roughly going by these rules:

- All SIG Release leadership should be in `sig-release-leads` and `release-team-leads`
- Only Release Managers and Release Manager Associates should be in `release-managers`
- Only _full-fledged_ members of both Release Managers and the Product Security Committee should be in `security-release-team`

/hold
/retitle slack-config: Add Jeremy Rickard as a SIG Release Technical Lead

2021-01-14 02:13 UTC, justaugustus commented on communication/slack-config/sig-release/usergroups.yaml
> +      - jeremyrickard # subproject owner / Release Manager
Drop.

2021-01-14 02:13 UTC, justaugustus commented on communication/slack-config/sig-release/usergroups.yaml
> +      - jeremyrickard # subproject owner / Release Manager
Drop.

2021-01-15 00:27 UTC, hasheddan commented
@justaugustus updates made :+1:

2021-01-15 00:29 UTC, justaugustus commented
Awesome, thanks @hasheddan!
/lgtm
/approve
/hold cancel

2021-01-15 00:31 UTC, merged