Add link to sig list
kubernetes/community pull request #5412
Opened 2021-01-15 01:47 UTC by cainejette

**Which issue(s) this PR fixes**:

Fixes #

2021-01-15 01:49 UTC, guineveresaenger commented
/ok-to-test
/lgtm

2021-01-15 01:57 UTC, mrbobbytables requested changes

2021-01-15 01:57 UTC, mrbobbytables commented on contributors/guide/first-contribution.md
> +[Special Interest Groups](./sig-list.md), or SIGs.
```suggestion
[Special Interest Groups][sl], or SIGs.
```
`./sig-list.md` would map to a file in the same directory and still break.

The link is there, but at the bottom of the doc as a reference link (`[sl]`)

```
[sl]: /sig-list.md
```

2021-01-15 23:36 UTC, mrbobbytables commented
Thanks! - one last thing - before we can accept the PR, can you sign the CLA?^^;;

2021-01-16 15:52 UTC, mrbobbytables commented
/check-cla

2021-01-31 17:27 UTC, mrbobbytables commented
/check-cla

2021-03-08 02:54 UTC, mrbobbytables commented
/check-cla

2021-03-08 23:52 UTC, cainejette commented
@mrbobbytables I don't plan to sign the CLA so please feel free to take this PR over

2021-03-09 00:14 UTC, mrbobbytables commented
Thanks for letting us know!
/close

2021-03-09 00:14 UTC, closed without merging