Update SIG Release versioning docs
kubernetes/community pull request #5632
Opened 2021-03-15 12:00 UTC by saschagrunert

The schedule now reflects the currently applied release schedule with
respect to alpha, beta and rc releases. We also drop the word `Kube` in
front of every release.

Some formatting nits have been fixed as well.

2021-03-15 12:00 UTC, saschagrunert commented
cc @kubernetes/release-engineering

2021-03-15 12:02 UTC, hasheddan approved these changes
/lgtm

2021-03-15 12:08 UTC, justaugustus commented
/hold

2021-03-15 12:13 UTC, justaugustus requested changes
@saschagrunert -- This is a legacy design proposal, so no one should be actively looking at these for accurate information.

Can we do the following instead:
1. File the updated version of this as k/release/versioning.md
2. Once that merges, add a note to the top of this proposal that the content therein is not the current state of the world and point them to the new doc

2021-03-16 08:05 UTC, saschagrunert commented
@justaugustus updated the PR to link to the new location

2021-03-16 15:54 UTC, justaugustus requested changes
@saschagrunert -- Echoing the previous review:

> Once that merges, add a note to the top of this proposal that the content therein is not the current state of the world and point them to the new doc

I think this document should continue to exist for historical purposes.
(This is part of the reason this directory has a blockade enabled on it.)

Disambiguating between "proposal" and "policy"... we wouldn't delete a KEP, but instead track policy updates in whichever living document existed (in this case: https://github.com/kubernetes/sig-release/blob/master/release-engineering/versioning.md).

2021-03-17 08:10 UTC, saschagrunert commented
> I think this document should continue to exist for historical purposes.
> (This is part of the reason this directory has a blockade enabled on it.)

Makes sense, I'll changed the doc as suggested.

2021-07-19 07:21 UTC, saschagrunert commented
@justaugustus PTAL
/remove-lifecycle rotten

2021-08-17 02:03 UTC, justaugustus requested changes
@saschagrunert -- Some minor language/emphasis suggestions.

2021-08-17 02:03 UTC, justaugustus commented on contributors/design-proposals/release/versioning.md
> +repository.
```suggestion
**This design proposal does NOT reflect the current state of Kubernetes versioning.**

**Up-to-date versioning policies can be found [here](https://git.k8s.io/sig-release/release-engineering/versioning.md).**
```

2021-08-17 07:35 UTC, saschagrunert commented
Updated as suggested :+1:

2021-08-17 23:18 UTC, justaugustus commented
/lgtm
/approve
/hold cancel

2021-08-17 23:20 UTC, justaugustus commented
Needs a repo admin to manually remove the blocked-paths label.
/assign @mrbobbytables @cblecker

2021-08-18 00:06 UTC, mrbobbytables commented
Thanks for the cc,
I've removed the label and it should be good to go 👍

2021-08-18 00:10 UTC, merged

2021-08-18 00:57 UTC, justaugustus commented
Thanks Bob!