bringing group mentoring program current
kubernetes/community pull request #5653
Opened 2021-03-22 18:15 UTC by parispittman

Co-authored-by: Elana Hashman <ehashman@redhat.com>

2021-03-22 18:20 UTC, ehashman commented
/assign

2021-04-07 19:53 UTC, ehashman requested changes

2021-04-07 19:53 UTC, ehashman commented on mentoring/programs/group-mentoring.md
>  months. Want to get `/lgtm` rights? Be a decision maker in an OWNERS file? This
```suggestion
groups are semi-structured learning environments over the course of a
release. Want to get `/lgtm` rights? Be a decision maker in an OWNERS file? This
```

Suggest we lock this to the release cycle.

2021-04-07 19:53 UTC, ehashman commented on mentoring/programs/group-mentoring.md
> +the key.
```suggestion
key.
```

2021-04-07 19:53 UTC, ehashman commented on mentoring/programs/group-mentoring.md
> +Member -> Reviewer | Reviewer -> Owner | Member/Reviewer/etc -> Chair
```suggestion
Member -> Reviewer | Reviewer -> Approver | SIG Member -> Chair
```

2021-04-07 19:53 UTC, ehashman commented on mentoring/programs/group-mentoring.md
> +- Three months
```suggestion
- Three months/one release cycle
```

2021-04-07 19:53 UTC, ehashman commented on mentoring/programs/group-mentoring.md
> + Folks want to know you are dependable and understand the domain.
```suggestion
 For you to progress, the community wants to know you are dependable and understand the domain.
```

2021-04-07 19:53 UTC, ehashman commented on mentoring/programs/group-mentoring.md
> +- At least the same level as the goal of the group (example: Reviewers for
```suggestion
- At least the same level as the goal of the group (example: Reviewer for 
```

2021-04-07 19:53 UTC, ehashman commented on mentoring/programs/group-mentoring.md
> +- Time committment: one dedicated day of slack triage and at least a 30 minute
```suggestion
- Time commitment: facilitate biweekly, hour long zoom sessions plus curriculum planning in between sessions (~1-2h/wk total).
```

2021-04-07 20:06 UTC, markyjackson-taulia approved these changes
/lgtm

2021-04-14 03:21 UTC, ehashman reviewed
/lgtm

2021-04-14 03:22 UTC, merged