Add annual report for SIG-MC
kubernetes/community pull request #5669
Opened 2021-03-30 15:39 UTC by JeremyOT

**Which issue(s) this PR fixes**:

Fixes #5505

2021-03-30 15:40 UTC, JeremyOT commented
/cc @pmorie
/assign @parispittman
/hold

2021-03-31 07:16 UTC, makkes approved these changes

2021-03-31 08:52 UTC, hectorj2f approved these changes

2021-04-02 16:35 UTC, parispittman requested changes

2021-04-05 15:42 UTC, pmorie commented on sig-multicluster/annual-report-2021.md
> +  * Due to the increase in activity in 2020, SIG meetings went from bi-weekly to weekly and almost always have a solid agenda.
That's a really good question and I'm not sure there's a clear answer, here are some factors that may be related:

- Calls for participation during Kubecon
- More focused work on individual problems (cluster ID, multicluster services, work) vs large-scoped efforts (federation)

2021-04-05 15:43 UTC, pmorie commented on sig-multicluster/annual-report-2021.md
> +  * We'd love to see more participation, more contributors bringing their perspectives and use cases.
Personally, I think we have capacity for folks to help moving any of our focused efforts (mentioned in above comment) forward in terms of hands-on code or technical writing.

2021-04-06 20:41 UTC, JeremyOT commented on sig-multicluster/annual-report-2021.md
> +  * SIG MC needs help with all of the above - especially when it comes to use cases and validating our approaches for different environments and deployment models.
We haven't and could use the help!

2021-04-06 20:41 UTC, JeremyOT commented on sig-multicluster/annual-report-2021.md
> +* Year to date KEP work review: What’s now stable? Beta? Alpha? Road to alpha?
Added timeframes

2021-04-06 20:41 UTC, JeremyOT commented on sig-multicluster/annual-report-2021.md
> +  * [Kubefed](http://sigs.k8s.io/kubefed) - long running subproject with active contribution.
Added the main 2020 Kubefed accomplishment.

2021-04-06 20:41 UTC, JeremyOT commented on sig-multicluster/annual-report-2021.md
> +  * [Work API](https://docs.google.com/document/d/1cWcdB40pGg3KS1eSyb9Q6SIRvWVI8dEjFp9RI0Gk0vg) - [sigs.k8s.io/work-api](https://sigs.k8s.io/work-api)
Right now, getting to beta is the primary goal for Kubefed in 2021

2021-04-06 20:42 UTC, JeremyOT commented on sig-multicluster/annual-report-2021.md
> +  * This SIG is in growth mode, and tries to create room for new ideas and projects driven by new and existing members alike. In 2020 we've seen two new initiatives kick off driven by relatively new
Good question - elaborated a bit more

2021-04-06 20:43 UTC, JeremyOT commented on sig-multicluster/annual-report-2021.md
> +  * Both SIG chairs are active and attend most SIG meetings.
We don't have other named roles, but I added a separate line to acknowledge Kubefed owners as they tend to operate mostly independently and prefer slack to the weekly meeting

2021-04-06 20:44 UTC, JeremyOT commented on sig-multicluster/annual-report-2021.md
> +  * Due to the increase in activity in 2020, SIG meetings went from bi-weekly to weekly and almost always have a solid agenda.
Good points, pulled this into the doc.

2021-04-06 20:44 UTC, JeremyOT commented on sig-multicluster/annual-report-2021.md
> +  * We'd love to see more participation, more contributors bringing their perspectives and use cases.
Made a node in the doc

2021-04-09 04:16 UTC, parispittman commented
/lgtm with steering hat on 

pull the hold in ~24 hours or so for last comments

2021-04-09 21:22 UTC, dims commented
/committee steering

2021-04-12 00:50 UTC, JeremyOT commented
Looks like there are no new comments. Thanks all!

/hold cancel

2021-04-13 16:07 UTC, parispittman commented
/lgtm

2021-04-13 16:10 UTC, merged