add documentation for verify-api-groups
kubernetes/community pull request #5829
Opened 2021-06-12 08:24 UTC by pravarag

**Which issue(s) this PR fixes**:

Fixes #5532

As part of this PR, documentation for test `verify-api-groups` have been added.

/sig testing

2021-06-14 16:55 UTC, spiffxp requested changes
Thank you for helping out!  Some suggestions to try and reduce the amount of text someone needs to read to answer "what is this verifying?"

2021-06-14 16:55 UTC, spiffxp commented on contributors/devel/sig-testing/verify-tests.md
> +
Should implies convention, use 'must' instead if it's a hard requirement.  Remove implementation details and extra blank line
```suggestion
the respective `register.go` file. Every register file must contain
a `GroupName`.
```

2021-06-14 16:55 UTC, spiffxp commented on contributors/devel/sig-testing/verify-tests.md
> +
Remove implementation detail
```suggestion
```

2021-06-14 16:55 UTC, spiffxp commented on contributors/devel/sig-testing/verify-tests.md
> +aren't served from API server.
```suggestion
Another check which is performed when this script runs is to ensure
that all types have client code generated for them, except types that
belong to groups not served from the API server (defined in this 
script via the bash array `groups_without_codegen`)
```

2021-06-14 16:55 UTC, spiffxp commented on contributors/devel/sig-testing/verify-tests.md
> +which are required without instllation along with importing
```suggestion
which are required without installation along with importing
```

2021-06-14 16:55 UTC, spiffxp commented on contributors/devel/sig-testing/verify-tests.md
> +In the last check of the script, we check for `import_known_versions`
```suggestion
Next, the script compares the `GroupName`s against `import_known_versions.go`
```

2021-06-14 16:55 UTC, spiffxp commented on contributors/devel/sig-testing/verify-tests.md
> +are in the init.sh file.
```suggestion
Finally the script checks that all external group versions (e.g. `foobar/v1`) are defined
in `hack/lib/init.sh` in either the `KUBE_AVAILABLE_GROUP_VERSIONS` or
`KUBE_NONSERVER_GROUP_VERSIONS` bash variables
```

2021-06-14 16:55 UTC, spiffxp commented
/ok-to-test

2021-06-16 15:14 UTC, pravarag commented on contributors/devel/sig-testing/verify-tests.md
> +are in the init.sh file.
Updated as per suggestion.

2021-06-16 15:14 UTC, pravarag commented on contributors/devel/sig-testing/verify-tests.md
> +aren't served from API server.
Updated as per suggestions

2021-06-16 15:15 UTC, pravarag commented
I've updated the code as suggested in review comments.

2021-06-17 21:48 UTC, spiffxp approved these changes
/approve
/lgtm

2021-06-17 21:52 UTC, merged