Contributor Comms reorganization
kubernetes/community pull request #5989
Opened 2021-09-03 17:01 UTC by mbbroberg

Significant clean up effort for Upstream Marketing documentation
focused on:

- Ensure roles described how the team has functioned over the last year
- Fill in stale TODOs with solid information
- Organize resources into the storytelling folder

Signed-off-by: Matthew Broberg <matt@opensource.com>

2021-09-03 17:06 UTC, mbbroberg commented
Hey @parispittman and @mrbobbytables, I did some work to tidy up based on a few discussions of @kaslin @rajula96reddy @chris-short and myself. Please take a look as time permits and happy to chat or async about the specifics.

2021-09-03 17:06 UTC, mbbroberg commented
/retest

2021-09-17 17:51 UTC, mbbroberg commented
/test pull-community-verify

2021-09-24 23:04 UTC, parispittman commented
communication/marketing-team/role-handbooks/council.md:9:115: "Coucil" is a misspelling of "Council"

looks great!! I think having each role get defined terms would be the next iteration. Many of the named roles outside of reviewer and approver have terms on the project and that helps escalate the shadow program behind it as well. Examples: two years for steering committee, release team is 3 months per role but building up to lead which will be ~9 months, event team is per event, etc.

2021-09-24 23:05 UTC, parispittman commented
/hold for steering lgtms 

steering - there is minor change here to the new example roles section in sig-governance.md

2021-10-08 15:44 UTC, mbbroberg commented
Thanks for the review @parispittman! I fixed the typo and reformatted the table to show available shadow opportunities by roles in practice of Program Lead, Promotion Lead, and Liaison Lead. I hope that helps. 

Note we have a lot of interest in shadow opportunities that we're hoping to review the week after KubeCon. I'm hopeful we can get this merged by that timeline if that could work.

2021-11-03 20:49 UTC, mbbroberg commented
Oops, seems I left this incomplete. Going to rerun tests now: 

/retest-required

2021-11-09 19:50 UTC, justaugustus commented
> Oops, seems I left this incomplete. Going to rerun tests now:
> 
> /retest-required

@mbbroberg -- Ping on the test fixes :)

```console
Verifying verify-spelling.sh
communication/marketing-team/README.md:13:120: "avaiable" is a misspelling of "available"
exit status 2
FAILED   verify-spelling.sh	2s 
```

ref: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/community/5989/pull-community-verify/1456000700650622976

2021-11-10 13:49 UTC, mbbroberg commented
@justaugustus you're a gentleman and a scholar 🙇

2021-11-10 15:28 UTC, justaugustus requested changes
Itty bitty style nit in `committee-steering/governance/sig-governance.md`.

Since you're in the neighborhood, it would be super appreciated if you'd be up for conforming the other links at the bottom of that doc to the style guide (in a separate commit).

No biggie, if not! :)

2021-11-10 15:28 UTC, justaugustus commented on committee-steering/governance/sig-governance.md
> +[Marketing Council]: https://github.com/kubernetes/community/blob/master/communication/marketing-team/role-handbooks/council.md
```suggestion
[Marketing Council]: /communication/marketing-team/role-handbooks/council.md
```

Style nit per https://github.com/kubernetes/community/blob/master/contributors/guide/style-guide.md#links.

2021-11-12 16:31 UTC, mbbroberg commented
@justaugustus thank you thank you for the nit / nudges 🙏 -- it's always nice to be helpful when I'm in the neighborhood. I'll update that and then, @parispittman, how are we looking on the front of removing the hold?

2021-11-12 20:16 UTC, chris-short commented
This is an amazing body of work @mbbroberg. Thank you.

2021-11-12 21:26 UTC, justaugustus approved these changes
> @justaugustus thank you thank you for the nit / nudges 🙏 -- it's always nice to be helpful when I'm in the neighborhood. I'll update that and then, @parispittman, how are we looking on the front of removing the hold?

@mbbroberg -- Thanks so much!
Changes to `committee-steering/governance/sig-governance.md` look great, so approving on behalf of Steering.
/approve

Feel free to lift the hold once you get an /lgtm + /approve from @kubernetes/sig-contributor-experience / Marketing folks!

2021-11-12 21:28 UTC, justaugustus commented
> Feel free to lift the hold once you get an /lgtm + /approve from @kubernetes/sig-contributor-experience / Marketing folks!

/assign @parispittman @rajula96reddy @kaslin

2021-11-16 22:48 UTC, parispittman commented
/lgtm
/hold cancel

2021-11-16 22:52 UTC, merged