Add code review guide
kubernetes/community pull request #6291
Opened 2021-12-13 18:18 UTC by sftim

Migrate the code review guide into its own document.
This incorporates some text taken from https://k8s.io/docs/contribute/review/for-approvers/

Ideally, SIG Docs can replace https://k8s.io/docs/contribute/review/for-approvers/ and have it redirect to this new page.

/area contributor-guide
Related to https://github.com/kubernetes/test-infra/issues/24660

2021-12-13 18:18 UTC, sftim commented
Once / if this merges, I can update the repo for https://k8s.dev/ to publish it there too.

2021-12-13 18:18 UTC, sftim commented
/sig docs

2021-12-14 13:20 UTC, mrbobbytables requested changes
I am okay with breaking this out for now, but as an FYI the entire guide is going to be rewritten and to dedupe a lot of the information and tell a complete story from start to finish. E.g. there really isn't a need for the review process to be in 2 locations (as it is now).

2021-12-14 13:20 UTC, mrbobbytables commented on contributors/guide/review-process.md
> +[OWNERS Files](https://www.kubernetes.dev/docs/guide/owners/) explains how `OWNERS` files work
```suggestion
[OWNERS Files](owners.md) explains how `OWNERS` files work
```
Please update all links to be relative to their location here in k/community. The files need to be browsable here and will be ingested and updated as part of generating the contributor site.

2021-12-14 13:20 UTC, mrbobbytables commented on contributors/guide/review-process.md
> +description: |
A weight is needed and the other files updated accordingly.

2021-12-14 14:08 UTC, sftim commented
If there's a rewrite, it'd be great to incorporate the information that's currently in the docs contribution guide as well.
Can SIG Docs help with that work?

2021-12-14 14:14 UTC, mrbobbytables commented
@sftim yup!
I'll cc you on the thread in slack

2022-05-13 16:11 UTC, closed without merging