Broken "Contributor Role Board" link in the first-contribution guide is updated to Community Issues
kubernetes/community pull request #6495
Opened 2022-02-24 16:45 UTC by uroy-personal

**Which issue(s) this PR fixes**:

Fixes #

2022-02-28 14:17 UTC, mrbobbytables requested changes
Thanks for the fix, one suggestion - we should direct folk to any good first issue or help wanted issue, and not directly to k/community. There are a lot of other places throughout the project that have them :)

2022-02-28 14:17 UTC, mrbobbytables commented on contributors/guide/first-contribution.md
> +[Community Issues]: https://github.com/kubernetes/community/issues
```suggestion
[issues labeled as a good first issue]: https://go.k8s.io/good-first-issue
```

corresponding link

2022-02-28 14:17 UTC, mrbobbytables commented on contributors/guide/first-contribution.md
> +[Community Issues] to see who is looking for help. Those interested
```suggestion
[issues labeled as a good first issue] to see who is looking for help. Those interested 
```

We should direct folks to any good first issue 👍

2022-02-28 14:29 UTC, uroy-personal commented
> Thanks for the fix, one suggestion - we should direct folk to any good first issue or help wanted issue, and not directly to k/community. There are a lot of other places throughout the project that have them :)

Thanks @mrbobbytables,
Appreciate your suggestions. Have committed the changes.

2022-02-28 14:30 UTC, uroy-personal reviewed
Suggestions accepted.

2022-02-28 17:58 UTC, tpepper commented
This looks good to me, but we'll want to squash and merge and for that the PR should have a clean description which will be recorded with the merge commit.  Can you either manually squash into a single commit with a clean description, or edit the description of the PR in GitHub to include even just a copy/paste of the description from https://github.com/kubernetes/community/issues/6493 ?

2022-02-28 19:23 UTC, uroy-personal commented
Hi @tpepper ,
Thanks for the suggestion.
The pull request description has been updated to make it same as the description of the issue covered by the pull request.

2022-03-01 20:55 UTC, tpepper commented
/ok-to-test
/lgtm
/approve

2022-03-01 20:57 UTC, merged