Update channels.yaml
kubernetes/community pull request #6638
Opened 2022-05-05 16:00 UTC by pkchavva

Adding a crossing channel #finsops to enable folks in the Kubernetes community to engage and participate with the FinOps Community.
Right now,the FinOps Slack is restricted to members who are certified. This channel is to allow the FInOps SIGs focused on Kubernetes(and containers) to have a broader conversation with the Kubernetes Community.

**Which issue(s) this PR fixes**:

Fixes #

2022-05-23 16:28 UTC, castrojo commented
/lgtm

2022-07-05 20:24 UTC, markyjackson-taulia requested changes

2022-07-05 20:24 UTC, markyjackson-taulia commented on communication/slack-config/channels.yaml
> +   -name: finops
The spacing is off with the -

2022-07-20 19:19 UTC, markyjackson-taulia commented
@castrojo wanted to check back on this

2022-07-28 13:46 UTC, markyjackson-taulia commented
@castrojo circling back on this

2022-09-26 14:53 UTC, castrojo commented
/approve

Sorry it took so long!

2022-09-30 18:30 UTC, jdumars commented
@castrojo bad news - the checks are not passing

2022-09-30 20:10 UTC, markyjackson-taulia commented
It now has just dawned on me that I was tagging @castrojo as the author but it really is @pkchavva 😮‍💨 

@pkchavva on line 110, you `-` is off, you need to line it up with the other `-` above, that will fix this.

2022-10-02 14:56 UTC, pkchavva commented on communication/slack-config/channels.yaml
> +   -name: finops
Done!

2022-10-02 14:57 UTC, pkchavva commented
> It now has just dawned on me that I was tagging @castrojo as the author but it really is @pkchavva 😮‍💨
> 
> @pkchavva on line 105, your `-` is off, you need to line it up with the other `-` above, that will fix this.

Let me know if this worked.

My first contribution so wasn't sure how to submit a patch.

2022-10-02 15:00 UTC, markyjackson-taulia approved these changes
/lgtm

2022-10-02 15:00 UTC, merged