Updated the security-profile-operator reference
kubernetes/community pull request #6786
Opened 2022-08-12 19:19 UTC by vaibhav2107

This PR does a minor update in the link to the OWNERS of sub-project security-profile-operator that is referenced under SIG node README page.

2022-08-12 19:23 UTC, markyjackson-taulia commented
/ok-to-test

2022-08-12 19:31 UTC, markyjackson-taulia requested changes
@vaibhav2107 Did you run the make generate after making the file changes? If not, please do so locally in this repo.. See https://github.com/kubernetes/community/blob/75e8013d560a8bc204c122a42c95326a2273b700/generator/README.md#how-to-use

2022-08-12 19:59 UTC, vaibhav2107 commented
@markyjackson-taulia yes,  will update it

2022-08-12 20:17 UTC, vaibhav2107 commented
@markyjackson-taulia PTAL

2022-08-12 20:18 UTC, markyjackson-taulia approved these changes
Thank you
/lgtm

2022-08-12 20:24 UTC, vaibhav2107 commented
/assign @nikhita

2022-08-30 00:28 UTC, jberkus commented
/approve

2022-08-30 00:31 UTC, merged