Update awards playbook
kubernetes/community pull request #6791
Opened 2022-08-15 19:38 UTC by reylejano

This PR updates the awards playbook with additional suggestions on how the community can be involved with awards and how SIGs can model awards to their own needs/goals.

2022-08-15 19:50 UTC, reylejano commented
@tokt  @jrsapi @parispittman ptal

2022-08-15 19:59 UTC, jberkus commented on events/awards/playbook.md
> +  - Most reviews or best reviewer
```suggestion
  - Most reviews or best reviewer
  - Team builder
  - KEP wrangler
```
... I'd like to have at least one non-code example there

2022-08-15 20:00 UTC, jberkus requested changes
Nice!

Please see suggestion for some non-code examples.

2022-08-15 20:12 UTC, tokt commented
/lgtm and thank you!

2022-08-16 18:45 UTC, jberkus commented
/lgtm
/approve

2022-08-16 18:46 UTC, merged