Update CHARTER.md
kubernetes/community pull request #7029
Opened 2023-01-06 18:53 UTC by chris-short

Refreshing post name change

**Which issue(s) this PR fixes**:

Fixes # N/A

While creating the Subproject Lead Handbook, @kaslin and I realized the CHARTER.md was out of date and improvements could be made.

We will ping the Slack channel this week and bring it up in our meeting next week. Lazy concensus will begin after meeting.

2023-01-06 18:54 UTC, chris-short commented
/assign @kaslin 

/hold

Waiting for next meeting to discuss changes.

2023-01-06 23:11 UTC, jberkus requested changes
A few typos, plus all of the new links you added are absolute links against your fork of the repository.  Please use relative links where possible, and where not possible link the master branch of the main repo.  Thanks!

2023-01-06 23:11 UTC, jberkus commented on communication/contributor-comms/CHARTER.md
> +* [Storytellers](https://github.com/chris-short/community/blob/master/communication/contributor-comms/role-handbooks/storytellers.md) & other members
Bad links

2023-01-06 23:11 UTC, jberkus commented on communication/contributor-comms/CHARTER.md
> +The Contributor Comms subproject welcomes and encourages its members to take on leadership roles in their contributions. The group defines the areas of its work such as social media, blogging, etc. a
bad link

2023-01-06 23:11 UTC, jberkus commented on communication/contributor-comms/CHARTER.md
> +Leads have the responsibility and autonomy to decide what is right for their portion of the groupl's division of work. The same escalation path can be used in case of disagreement that cannot be reso
typo "group"

2023-01-06 23:11 UTC, jberkus commented on communication/contributor-comms/CHARTER.md
> +Decisions affecting all of Contributor Comms are made primarily led by the Contributor Comms Subproject Lead[s]. Decisions are generally made by lazy consensus with the goal of everyone getting a say
lead(s)

2023-01-13 16:09 UTC, closed without merging

2023-01-13 16:20 UTC, chris-short commented
@jberkus Noted. Lost my local copy. Will open a new PR shortly.