Update the user group for Cluster API release team
kubernetes/community pull request #7230
Opened 2023-03-30 18:02 UTC by joekr

This PR updates the slack user group for the Cluster API release team.

**Which issue(s) this PR fixes**:

Fixes #

2023-03-30 18:03 UTC, ykakarap approved these changes
/lgtm

2023-04-02 14:12 UTC, furkatgofurov7 reviewed
Thanks, lgtm except a small nit:

The list seemed to be sorted alphabetically previously, maybe we should keep the new one the same way?

2023-04-02 15:10 UTC, furkatgofurov7 requested changes

2023-04-02 15:10 UTC, furkatgofurov7 commented on communication/slack-config/usergroups.yaml
> -      - joekr
hmm, so you are being removed from the team here :)

2023-04-02 15:21 UTC, furkatgofurov7 reviewed
/lgtm

2023-04-04 14:38 UTC, chrischdi reviewed
/lgtm

2023-04-04 16:47 UTC, jeefy commented
/approve

2023-04-04 16:49 UTC, merged