Generate 2023 Annual Report boilerplates
kubernetes/community pull request #7717
Opened 2024-02-13 18:40 UTC by palnabarun

Generate 2023 Annual Report boilerplates

/committee steering
cc: @kubernetes/steering-committee

2024-02-13 19:56 UTC, soltysh approved these changes
/lgtm
/hold
for others to chime in

2024-02-14 07:21 UTC, pohly commented
Nit: "kubecon"  -> "KubeCon", but let's not bother fixing this.

/lgtm

2024-02-19 08:33 UTC, pacoxu commented
/lgtm

2024-02-22 15:13 UTC, mrbobbytables commented on generator/annual-report/sig_report.tmpl
> +-->
I think for this we should move it above the generated content, that way its a clear thing between user supplied content and generated content.

2024-03-06 16:32 UTC, BenTheElder commented
/lgtm

2024-03-06 16:38 UTC, justaugustus requested changes
Quick fix

2024-03-06 16:38 UTC, justaugustus commented on generator/annual-report/sig_report.tmpl
> +2.Are there any areas and/or subprojects that your group needs help with (e.g. fewer than 2 active OWNERS)?
```suggestion
2. Are there any areas and/or subprojects that your group needs help with (e.g. fewer than 2 active OWNERS)?
```

2024-03-06 16:38 UTC, justaugustus commented on generator/annual-report/wg_report.tmpl
> +2.Are there any areas and/or subprojects that your group needs help with (e.g. fewer than 2 active OWNERS)?
```suggestion
2. Are there any areas and/or subprojects that your group needs help with (e.g. fewer than 2 active OWNERS)?
```

2024-03-06 17:19 UTC, palnabarun commented
@mrbobbytables @BenTheElder @justaugustus -- all comments are resolved. Can you re-LGTM?

2024-03-06 18:03 UTC, BenTheElder commented
/lgtm

2024-03-06 18:50 UTC, BenTheElder commented
/hold cancel

2024-03-06 18:54 UTC, merged