Adds exported kubernetes.io analytics data from universal analytics
kubernetes/community pull request #7757
Opened 2024-03-13 18:42 UTC by a-mccarthy

Adds in a new folder and cvs files of reports exported from Universal anayltics

2024-03-13 18:45 UTC, a-mccarthy commented
@sftim @natalisucks @reylejano @divya-mohan0209, added in analytics report exports here, but i'm not sure if this is the best place. We could also have them in google sheets, or in the website repo.

I can also grab more reports, or make the reports smaller if we dont need to keep as much information

2024-03-13 19:03 UTC, sftim commented
I agree with this change.

2024-03-13 19:04 UTC, sftim commented
> ```
>  sig-docs/analytics/top-search-terms.csv:197:0: "persistant" is a misspelling of "persistent" 
> ```

It is, but I'm not sure we can fix people. Maybe we ought to exempt CSV files there? @a-mccarthy want some help with that part?

2024-03-14 00:55 UTC, divya-mohan0209 requested changes
Small amendment, but overall I agree with the changes.

2024-03-14 00:55 UTC, divya-mohan0209 commented on sig-docs/analytics/README.md
> + [top-pages-by-pageviews.csv](/top-blogs-by-pageview.cvs) has a table for the top 500 pages by views for the date range and a table with the total number of pageviews for each day in the range.
```suggestion
 [top-pages-by-pageviews.csv](/top-blogs-by-pageview.csv) has a table for the top 500 pages by views for the date range and a table with the total number of pageviews for each day in the range. 
```

2024-03-14 13:48 UTC, a-mccarthy commented
> Maybe we ought to exempt CSV files there? @a-mccarthy want some help with that part?

Yes, @sftim if you could point me where to make that change, i'll be happy to try!

2024-03-24 18:37 UTC, sftim commented
I'll try to make time for that advice.

2024-05-03 11:27 UTC, sftim commented
Sorry, I didn't find time yet.

2024-06-03 14:04 UTC, a-mccarthy commented on sig-docs/analytics/README.md
> + [top-pages-by-pageviews.csv](/top-blogs-by-pageview.cvs) has a table for the top 500 pages by views for the date range and a table with the total number of pageviews for each day in the range.
updated, thanks @divya-mohan0209

2024-09-01 14:31 UTC, divya-mohan0209 commented
/remove-lifecycle stale

2025-01-29 16:13 UTC, closed without merging