Add Kat Cosgrove as SIG Docs tech lead
kubernetes/community pull request #7893
Opened 2024-05-13 08:28 UTC by katcosgrove

Adding myself as SIG Docs tech lead!

2024-05-13 08:35 UTC, tengqm commented
/test pull-community-verify

2024-05-13 08:36 UTC, tengqm commented on sig-docs/README.md
> +* Kat Cosgrove (**[@katcosgrove](https://github.com/katcosgrove)**), Dell Technologies
Sounds like we are not supposed to manually edit this file. It will be updated by some mysterious scripts.

2024-05-13 15:10 UTC, mrbobbytables commented
/retest

2024-05-14 01:48 UTC, tengqm commented
There is a conflict to be resolved for this PR. @katcosgrove

2024-06-05 22:27 UTC, justaugustus requested changes
@katcosgrove — you'll need to make the requisite updates in `sigs.yaml` and then run `make generate`, which will update references in `OWNERS_ALIASES` and the SIG Docs readme.

ref: https://github.com/kubernetes/community/tree/master/generator/README.md

2024-06-05 22:27 UTC, justaugustus commented on OWNERS_ALIASES
> +    - katcosgrove
This will get automatically generated.

2024-06-19 06:23 UTC, Okabe-Junya commented
FYI: https://github.com/kubernetes/community/pull/7946#issuecomment-2177842684

> Yes, I also think that moving this PR forward is easier. (Please note that 7893 has not been updated for about two weeks.)
> 
> However, if we moving this PR forward, 7893 will likely be closed. (This is not a major issue, but since 7893 was opened first, I thought it might be good to leave a brief comment.)

2024-06-19 11:18 UTC, justaugustus commented
Supercede by https://github.com/kubernetes/community/pull/7946

ref: https://github.com/kubernetes/community/pull/7946#issuecomment-2178423980

/close

2024-06-19 11:18 UTC, closed without merging