Fix docs blog readme
kubernetes/community pull request #7953
Opened 2024-06-24 03:55 UTC by AnshumanTripathi

**Which issue(s) this PR fixes**:

Fixes # https://github.com/kubernetes/community/issues/7952

2024-06-24 03:56 UTC, mengjiao-liu reviewed
/ok-to-test

2024-06-24 03:58 UTC, mengjiao-liu reviewed
/lgtm

2024-06-24 03:59 UTC, mengjiao-liu commented
/assign @reylejano

2024-06-24 12:30 UTC, lavishpal approved these changes

2024-06-24 12:31 UTC, lavishpal commented
/lgtm

2024-06-24 12:35 UTC, divya-mohan0209 requested changes
Can we use relative linking please instead of specifying the entire link?

2024-06-24 16:27 UTC, AnshumanTripathi commented
> Can we use relative linking please instead of specifying the entire link?

I have updated to use the relative but we use the complete URL in other places, for example - https://github.com/kubernetes/community/blob/384d42fec0e16929805f42ac9ac983061c2da084/sig-docs/README.md?plain=1#L106-L107. Should I update the other references under sig-docs as well?

2024-06-27 16:48 UTC, stmcginnis commented
> Should I update the other references under sig-docs as well?

That would be great - whether here or in another PR.

/lgtm

2024-07-21 06:38 UTC, AnshumanTripathi commented
> > Should I update the other references under sig-docs as well?
> 
> That would be great - whether here or in another PR.
> 
> /lgtm

Actually this might not be possible since the generator expects complete links.

2024-07-23 17:54 UTC, reylejano commented on sig-docs/README.md
> +  - [kubernetes/community/governance.md#subprojects](https://github.com/kubernetes/community/blob/master/governance.md#subprojects)
This area is a list of SIG Docs subprojects: blog, localization, reference-docs
I don't think the subproject and WG definition is needed here.

I think this place is better for the link to the subproject definition if it's not there
https://github.com/kubernetes/community/blob/master/governance.md#subprojects

And this place is better for the link to the WG definition if it's not there
https://github.com/kubernetes/community/blob/master/governance.md#working-groups

2024-07-23 17:55 UTC, reylejano commented on sigs.yaml
> +    - https://raw.githubusercontent.com/kubernetes/community/master/governance.md#working-groups
This area has SIG Docs named subprojects: blog, localization, reference-docs, website
The links to the definition of subproject and WG does not belong here

2024-07-23 17:55 UTC, reylejano commented on sig-docs/README.md
> +  - [kubernetes/community/governance.md#working-groups](https://github.com/kubernetes/community/blob/master/governance.md#working-groups)
I think this place is better for the link to the WG definition if it's not there
https://github.com/kubernetes/community/blob/master/governance.md#working-groups

This area is for named SIG Docs subprojects

2024-12-06 16:41 UTC, jayeshmahajan approved these changes

2025-05-05 17:52 UTC, closed without merging