Modify the sample link in #sign-the-cla section
kubernetes/community pull request #8057
Opened 2024-08-29 09:38 UTC by ziyi-xie

This PR aims to update the sample link in the [#sign-the-cla](https://www.kubernetes.dev/docs/guide/#sign-the-cla) section.
The current example does not follow the repository’s template, making it a little inconvenient for review. Therefore, I want to update it to adhere to the template.

2024-08-29 09:49 UTC, Priyankasaggu11929 commented
> This PR aims to update the sample link in the [#sign-the-cla](https://www.kubernetes.dev/docs/guide/#sign-the-cla) section. The current example does not follow the repository’s template, making it a little inconvenient for review. Therefore, I want to update it to adhere to the template.

@ziyi-xie, what's the difference between the 2 PRs? One with a file ending with markdown extension, other not?

2024-08-29 11:12 UTC, shu-mutou commented
How about adding a `Note:` that says, "kubernetes-sigs/contributor-playground is a repository for practicing submitting your first PR, not just for CLA registration. Please write your PR according to the template and submit it as practice."

2024-08-29 11:18 UTC, shu-mutou commented
@Priyankasaggu11929 The difference between the two PRs is not in the contents of the files to be changed, but in the PR description.
What is being pointed out here is that the PR shoud be written according to the purpose of the kubernetes-sigs/contributor-playground repository.
Thanks!

2024-08-29 11:50 UTC, Priyankasaggu11929 commented
Thanks for the clarification @shu-mutou. 

> How about adding a `Note:` that says, "kubernetes-sigs/contributor-playground is a repository for practicing submitting your first PR, not just for CLA registration. Please write your PR according to the template and submit it as practice."

yes, let's please add a similar note to above.

Without this, it's still not clear that we're asking people to `fill the PR description per the provided template in the repo`

2024-08-30 02:29 UTC, ziyi-xie commented
@shu-mutou Thank you for the additions!
@Priyankasaggu11929 I made modifications based on your suggestions, and the formatting(bold the Note and add the content after it) references [other sections in the same document](https://www.kubernetes.dev/docs/guide/issue-triage/#scope). Could you please take a look at the changes I've made and let me know if they meet your expectations? I'd appreciate your feedback.

2024-08-30 05:10 UTC, Priyankasaggu11929 requested changes
Left a few minor nit review for rewording.

Rest looks good to me. Thanks @ziyi-xie!

2024-08-30 05:10 UTC, Priyankasaggu11929 commented on contributors/guide/README.md
> +**Note:** kubernetes-sigs/contributor-playground repo is a repository for practicing submitting your first PR, not just for CLA registration. Please write your PR according to the template and submit
```suggestion
**Note:** [kubernetes-sigs/contributor-playground](https://github.com/kubernetes-sigs/contributor-playground) is a repository for practicing submitting your first PR, not just for CLA registration. When creating and submitting a new PR, please write the PR description according to the provided template. Check the above example PR for reference.
```

2024-08-30 06:49 UTC, Priyankasaggu11929 commented
/lgtm
/approve

Thanks so much again @ziyi-xie!

2024-08-30 06:51 UTC, merged

2024-08-30 06:54 UTC, ziyi-xie commented
@Priyankasaggu11929 Thank you so much for your help and prompt confirmation!