Hindi Category in Kubernetes Discussion
kubernetes/community pull request #8144
Opened 2024-11-12 01:53 UTC by jayeshmahajan

**Which issue(s) this PR fixes**:

Fixes #

2024-11-22 20:01 UTC, jayeshsub approved these changes

2024-12-04 23:34 UTC, jberkus requested changes
One change needed.

2024-12-04 23:34 UTC, jberkus commented on communication/moderators.md
> +[hindi]: https://discuss.kubernetes.io/c/regional-discussions/hindi/29
Fix link:

```suggestion
[hindi]: https://discuss.kubernetes.io/t/about-the-hindi-category/30051
```

2024-12-04 23:42 UTC, jayeshmahajan commented on communication/moderators.md
> +[hindi]: https://discuss.kubernetes.io/c/regional-discussions/hindi/29
Done

2024-12-05 20:13 UTC, jberkus commented
/ok-to-test

2024-12-06 00:05 UTC, jberkus commented
/approve
/lgtm

2024-12-09 23:19 UTC, jayeshmahajan commented
/assign [@MadhavJivrajani ](https://github.com/madhavjivrajani)

2024-12-10 01:29 UTC, MadhavJivrajani approved these changes
/approve
Thank you!

2024-12-10 01:32 UTC, merged